### ISSUE TITLE
[Search Forms] Can not save a search form with an empty date

### ISSUE THREAD

**Issue by Bdthomson** [codice/ddf#4993]
### Steps to Reproduce
Create a search form like this and attempt to save.

![image](https://user-images.githubusercontent.com/7236299/59796738-fc764280-9292-11e9-8bb9-770f6ebcee80.png)

#### Expected behavior :
Search form saves successfully.

#### Actual behavior:
Search form fails to save because in the backend, the date value is being parsed as `"null"` instead of `null`. Sometimes I've also seen the value be an empty string instead of `"null"`.

#### Reproduces how often:
100%

### Affects versions
2.16.0-SNAPSHOT
2.15.1

**Comment by Bdthomson** [comment]
Possibly fixed by https://github.com/codice/ddf/pull/5149?

**Comment by jordanwilking** [comment]
Still occurring on 2.18.0 SNAPSHOT as of commit [de4b1c3887dd7e5e396d08eb217c60775fbb4151](https://github.com/codice/ddf/commit/de4b1c3887dd7e5e396d08eb217c60775fbb4151)

<img src="https://user-images.githubusercontent.com/22667297/65058092-884a4a00-d928-11e9-8e5c-82f8c254e51a.png" height=50% width=50% />

<img src="https://user-images.githubusercontent.com/22667297/65058115-95673900-d928-11e9-9fae-236be7c31b3c.png" height=50% width=50% />
